/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab8p2_juanidiaquez;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanf
 */
public class Lab8P2_JuanIdiaquez extends javax.swing.JFrame {

    /**
     * Creates new form Lab8P2_JuanIdiaquez
     */
    public Lab8P2_JuanIdiaquez() {
        initComponents();
        
        ComboPActivacion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombrePais = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        NumeroMedallas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NombreNadador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ComboNacionalidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        EdadNadador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EstaturaNadador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ComboEstiloN = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        DistanciaNadador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        SpinnerTiempoM = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        SpinnerNMedallas = new javax.swing.JSpinner();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ComboDistancia = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        TextoRecord = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        ComboEstiloE = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaN = new javax.swing.JTable();
        jToggleButton4 = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaE = new javax.swing.JTable();
        jToggleButton5 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        BarraN1 = new javax.swing.JProgressBar();
        BarraN2 = new javax.swing.JProgressBar();
        BarraN3 = new javax.swing.JProgressBar();
        ComboES = new javax.swing.JComboBox<>();
        ComboN1E = new javax.swing.JComboBox<>();
        ComboN2E = new javax.swing.JComboBox<>();
        ComboN3E = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre ");

        NombrePais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePaisActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToggleButton1.setText("Crear");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        jLabel3.setText("Numero de Medallas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(355, 355, 355))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(NombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NumeroMedallas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(NumeroMedallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        jTabbedPane1.addTab("Crear Pais", jPanel1);

        jLabel2.setText("Nombre ");

        jLabel4.setText("Nacionalidad");

        jLabel5.setText("Edad");

        jLabel6.setText("Estatura");

        EstaturaNadador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstaturaNadadorActionPerformed(evt);
            }
        });

        jLabel7.setText("Estilo de Natacion ");

        ComboEstiloN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre ", "Pecho ", "Dorso ", "Mariposa " }));

        jLabel8.setText("Distancia");

        jLabel9.setText("Tiempo mas rapido ");

        jLabel10.setText("Numero de Medallas");

        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToggleButton2.setText("Crear");
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboEstiloN, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ComboNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DistanciaNadador, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SpinnerTiempoM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel10))
                        .addGap(178, 178, 178))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EstaturaNadador, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(EdadNadador, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(NombreNadador, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SpinnerNMedallas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(ComboEstiloN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(NombreNadador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ComboNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(DistanciaNadador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(SpinnerTiempoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(EdadNadador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SpinnerNMedallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(EstaturaNadador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Crear Nadador", jPanel2);

        jLabel11.setText("Estilo");

        jLabel12.setText("Distancia");

        ComboDistancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "400", "800" }));
        ComboDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDistanciaActionPerformed(evt);
            }
        });

        jLabel13.setText("Record en Segs");

        jToggleButton3.setText("Crear");
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
        });

        ComboEstiloE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre ", "Pecho ", "Dorso ", "Mariposa " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(ComboDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(ComboEstiloE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addComponent(ComboEstiloE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel12)
                .addGap(48, 48, 48)
                .addComponent(ComboDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel13)
                .addGap(36, 36, 36)
                .addComponent(TextoRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Evento", jPanel3);

        TablaN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nacionalidad", "Edad", "Estatura", "Estilo", "Distancia", "Tiempo mas rapido", "Medallas"
            }
        ));
        jScrollPane1.setViewportView(TablaN);

        jToggleButton4.setText("Listar");
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseClicked(evt);
            }
        });
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jToggleButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jToggleButton4)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla  Nadadores", jPanel4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tabla de ganadores", jPanel6);

        TablaE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Estilo", "Distancia", "RecordA"
            }
        ));
        jScrollPane2.setViewportView(TablaE);

        jToggleButton5.setText("Listar");
        jToggleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton5MouseClicked(evt);
            }
        });
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jToggleButton5)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jToggleButton5)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Eventos", jPanel7);

        ComboES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboESActionPerformed(evt);
            }
        });

        jLabel14.setText("Nadador1");

        jLabel15.setText("Nadador2");

        jLabel16.setText("Nadador3");

        jToggleButton6.setText("Simular");
        jToggleButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton6MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("Evento");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ComboN1E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboN2E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboN3E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BarraN3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BarraN2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BarraN1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(95, 95, 95))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(88, 88, 88))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboES, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboN1E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(ComboES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarraN1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20)
                .addComponent(ComboN2E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(BarraN2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BarraN3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboN3E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        jTabbedPane1.addTab("Simulacion", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombrePaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePaisActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        String Nombre= NombrePais.getText();
        int NMedallas= Integer.parseInt(NumeroMedallas.getText());
        Paises.add(new Pais(Nombre, NMedallas));
        DefaultComboBoxModel m = (DefaultComboBoxModel) ComboNacionalidad.getModel();
        
        for (int i = 0; i < Paises.size(); i++) {
            Pais p = Paises.get(i);
            m.addElement(p);
            
        }
        
        ComboNacionalidad.setModel(m);
        AgregarArchIvo(Paises.get(Paises.size()-1));
        JOptionPane.showMessageDialog(this, "Pais creado con exito");
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void EstaturaNadadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstaturaNadadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstaturaNadadorActionPerformed

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        String Nombre= NombreNadador.getText();
        String Nacionalidad=  ComboNacionalidad.toString();
        int edad = Integer.parseInt(EdadNadador.getText());
        double Estatura= Double.parseDouble(EstaturaNadador.getText());
        String Estilo="";
        if (((String) ComboEstiloN.getSelectedItem()).equals("Pecho")) {
           Estilo="Pecho";
        }
        if (((String) ComboEstiloN.getSelectedItem()).equals("Libre")) {
            Estilo="Libre";
        }
        if (((String) ComboEstiloN.getSelectedItem()).equals("Mariposa")) {
            Estilo="Mariposa";
        }
        if (((String) ComboEstiloN.getSelectedItem()).equals("Dorso")) {
            Estilo="Dorso";
        }
        int distancia= Integer.parseInt(DistanciaNadador.getText());
        int MejorT= ((Integer)SpinnerTiempoM.getValue());
        int NMedallas= ((Integer)SpinnerNMedallas.getValue());
        Nadador n= new Nadador(Nombre, Nacionalidad, edad, Estatura, Estilo, distancia, MejorT, NMedallas);
        Nadadores.add(n);
        AgregarArchIvo(Nadadores.get(Nadadores.size()-1));
        for (int i = 0; i < Paises.size(); i++) {
            String bandera= Paises.get(i).toString();
            String N=  ComboNacionalidad.toString();
            if (bandera.equals(N)) {
                Pais p= Paises.get(i);
                p.getNadadores().add(n);
            }
        }
        JOptionPane.showMessageDialog(this, "Nadador creado con exito");
        DefaultComboBoxModel m= (DefaultComboBoxModel) ComboN1E.getModel();
        m.addAll(Nadadores);
        ComboN1E.setModel(m);
        DefaultComboBoxModel x= (DefaultComboBoxModel) ComboN2E.getModel();
        x.addAll(Nadadores);
        ComboN2E.setModel(x);
        DefaultComboBoxModel y= (DefaultComboBoxModel) ComboN3E.getModel();
        y.addAll(Nadadores);
        ComboN3E.setModel(y);
    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void ComboDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboDistanciaActionPerformed

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked
        String Estilo="";
        if (((String) ComboEstiloE.getSelectedItem()).equals("Pecho")) {
           Estilo="Pecho";
        }
        if (((String) ComboEstiloE.getSelectedItem()).equals("Libre")) {
            Estilo="Libre";
        }
        if (((String) ComboEstiloE.getSelectedItem()).equals("Mariposa")) {
            Estilo="Mariposa";
        }
        if (((String) ComboEstiloE.getSelectedItem()).equals("Dorso")) {
            Estilo="Dorso";
        }
        String Distancia="";
        if (((String) ComboDistancia.getSelectedItem()).equals("100")) {
           Distancia="100";
        }
        if (((String) ComboDistancia.getSelectedItem()).equals("200")) {
            Distancia="200";
        }
        if (((String) ComboDistancia.getSelectedItem()).equals("400")) {
            Distancia="400";
        }
        if (((String) ComboDistancia.getSelectedItem()).equals("800")) {
            Distancia="800";
        }
        int distancia= Integer.parseInt(Distancia);
        int records= Integer.parseInt(TextoRecord.getText());
        eventos.add(new Eventos(Estilo, distancia, records));
        JOptionPane.showMessageDialog(this, "Evento creado con exito");
        AgregarArchIvoE(eventos.get(eventos.size()-1));
        DefaultComboBoxModel m= (DefaultComboBoxModel) ComboES.getModel();
        m.addAll(eventos);
        ComboES.setModel(m);
    }//GEN-LAST:event_jToggleButton3MouseClicked

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseClicked
        DefaultTableModel modelotabla=(DefaultTableModel)TablaN.getModel();
       
        for (int i = 0; i < Nadadores.size(); i++) {
        Object[] object={Nadadores.get(i).getNombre(),Nadadores.get(i).getNacionalidad(),Nadadores.get(i).getEdad(),Nadadores.get(i).getEstatura(),Nadadores.get(i).getEstiloN(),Nadadores.get(i).getDistancia(),Nadadores.get(i).getMejorTIempo(),Nadadores.get(i).getNumeroM()};
       modelotabla.addRow(object);
        }
        TablaN.setModel(modelotabla);
    }//GEN-LAST:event_jToggleButton4MouseClicked

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton5MouseClicked
        DefaultTableModel modelotabla = (DefaultTableModel) TablaE.getModel();

        for (int i = 0; i < eventos.size(); i++) {
            Object[] object = {eventos.get(i).Estilos, eventos.get(i).Distancia, eventos.get(i).RecordS};
            modelotabla.addRow(object);
        }
        TablaE.setModel(modelotabla);
    }//GEN-LAST:event_jToggleButton5MouseClicked

    private void ComboESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboESActionPerformed

    private void jToggleButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton6MouseClicked
        Eventos e = ((Eventos) ComboES.getSelectedItem());
        int Distancia= e.getDistancia();
        String Estilo= e.getEstilos();
        Nadador N1= ((Nadador)ComboN1E.getSelectedItem());
        Nadador N2= ((Nadador)ComboN2E.getSelectedItem());
        Nadador N3= ((Nadador)ComboN3E.getSelectedItem());
        boolean estilo= false;
        boolean distancia= false;
        if (Estilo.equalsIgnoreCase(N1.getEstiloN())) {
            if (Estilo.equalsIgnoreCase(N2.getEstiloN())) {
                if (Estilo.equalsIgnoreCase(N3.getEstiloN())) {
                    estilo=true;
                }
            }
        }
        if (Distancia==N1.getDistancia()) {
            if (Distancia==N2.getDistancia()) {
                if (Distancia==N3.getDistancia()) {
                    distancia=true;
                }
            }
        }
        
        if (distancia==true && estilo==true) {
            BarraN1 Nada1= new BarraN1(Distancia, BarraN1);
            Nada1.run();
            BarraN2 Nada2= new BarraN2(Distancia, BarraN2);
            Nada2.run();
            BarraN3 Nada3= new BarraN3(Distancia, BarraN3);
            Nada1.run();
            
            for (int i = 1; i < 4; i++) {
                int ran= (int) ((Math.random() * (20 - 0) + 0));
                if (Nada1.winner) {
                    if (Nada2.winner) {
                        if (Nada3.winner) {
                            switch (i) {
                                case 1:
                                    
                                    Nada1.setRandom(ran);
                                    break;
                                case 2:
                                    Nada2.setRandom(ran);
                                    break;
                                    case 3:
                                    Nada3.setRandom(ran);
                                    break;
                            }
                        }else{
                        i=10;
                        }
                    }else{
                        i=10;
                    }
                }else{
                    i=10;
                
                        }
                    }
                }
    }//GEN-LAST:event_jToggleButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_JuanIdiaquez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_JuanIdiaquez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_JuanIdiaquez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_JuanIdiaquez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab8P2_JuanIdiaquez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraN1;
    private javax.swing.JProgressBar BarraN2;
    private javax.swing.JProgressBar BarraN3;
    private javax.swing.JComboBox<String> ComboDistancia;
    private javax.swing.JComboBox<String> ComboES;
    private javax.swing.JComboBox<String> ComboEstiloE;
    private javax.swing.JComboBox<String> ComboEstiloN;
    private javax.swing.JComboBox<String> ComboN1E;
    private javax.swing.JComboBox<String> ComboN2E;
    private javax.swing.JComboBox<String> ComboN3E;
    private javax.swing.JComboBox<String> ComboNacionalidad;
    private javax.swing.JTextField DistanciaNadador;
    private javax.swing.JTextField EdadNadador;
    private javax.swing.JTextField EstaturaNadador;
    private javax.swing.JTextField NombreNadador;
    private javax.swing.JTextField NombrePais;
    private javax.swing.JTextField NumeroMedallas;
    private javax.swing.JSpinner SpinnerNMedallas;
    private javax.swing.JSpinner SpinnerTiempoM;
    private javax.swing.JTable TablaE;
    private javax.swing.JTable TablaN;
    private javax.swing.JTextField TextoRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    // End of variables declaration//GEN-END:variables
ArrayList <Pais> Paises = new ArrayList();
ArrayList <Nadador> Nadadores = new ArrayList();
ArrayList <Eventos> eventos = new ArrayList();
    
      public void AgregarArchIvo(Pais pais) {
        try {
            File Archivo = new File("./PaisesParticipantes.juan");
            FileOutputStream FW= new FileOutputStream(Archivo);
            ObjectOutputStream BW= new ObjectOutputStream(FW);
            BW.writeObject(pais);
            BW.flush();
            BW.close();
            FW.close();
        } catch (Exception e) {
        }
    }
    
    public ArrayList <Pais> LeerArchivos(ArrayList <Pais> Paises){
        ArrayList <Pais> paises = Paises;
        try {
            File Archivo = new File("./PaisesParticipantes.juan");
            FileInputStream FW= new FileInputStream(Archivo);
            ObjectInputStream BW= new ObjectInputStream(FW);
            Pais temporal= new Pais();
            while ((temporal= (Pais) BW.readObject()) !=null) {                
                paises.add(temporal);
            }
        } catch (Exception e) {
        }
        return paises;
    }

    public void ComboPActivacion(){
        Pais p = new Pais();
        ArrayList <Pais> Paises = new ArrayList();
        LeerArchivos(Paises);
        DefaultComboBoxModel m = (DefaultComboBoxModel) ComboNacionalidad.getModel();
        for (int i = 0; i < Paises.size(); i++) {
            Pais pp = Paises.get(i);
            m.addElement(pp);
            
        }
        ComboNacionalidad.setModel(m);
    }
    
    public void AgregarArchIvo(Nadador nadador) {
        try {
            File Archivo = new File("./Nadadores.juan");
            FileOutputStream FW= new FileOutputStream(Archivo);
            ObjectOutputStream BW= new ObjectOutputStream(FW);
            BW.writeObject(nadador);
            BW.flush();
            BW.close();
            FW.close();
        } catch (Exception e) {
        }
    }
    
    public ArrayList <Nadador> LeerArchivosN(ArrayList <Nadador> Nadadores){
        ArrayList <Nadador> nadadores = Nadadores;
        try {
            File Archivo = new File("./Nadadores.juan");
            FileInputStream FW= new FileInputStream(Archivo);
            ObjectInputStream BW= new ObjectInputStream(FW);
            Nadador temporal= new Nadador();
            while ((temporal= (Nadador) BW.readObject()) !=null) {                
                nadadores.add(temporal);
            }
        } catch (Exception e) {
        }
        return nadadores;
    }

     public void AgregarArchIvoE(Eventos eventos) {
        try {
            File Archivo = new File("./Eventos.juan");
            FileOutputStream FW= new FileOutputStream(Archivo);
            ObjectOutputStream BW= new ObjectOutputStream(FW);
            BW.writeObject(eventos);
            BW.flush();
            BW.close();
            FW.close();
        } catch (Exception e) {
        }
    }
    
    
}
